# Generated by Django 3.0.8 on 2020-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('take a walk', '散歩'), ('date plan', 'デート'), ('family trip', '家族旅行')], default='take a walk', max_length=12)),
            ],
        ),
    ]
