# Generated by Django 3.1 on 2020-09-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('take a walk', '散歩'), ('date plan', 'デート'), ('family trip', '家族旅行')], default='take a walk', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CardToCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(null=True)),
                ('price', models.PositiveIntegerField()),
                ('choice_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.placename')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('chara', models.CharField(choices=[('characteristic', '特徴'), ('landscape', '風景'), ('history', '歴史'), ('theme park', '遊園地'), ('leisure facilities', 'レジャー施設'), ('sports', 'スポーツ'), ('food', '食事処'), ('spring', '温泉'), ('amusement', '娯楽'), ('nature', '自然'), ('art', '芸術'), ('world heritage', '世界遺産'), ('souvenir', 'お土産')], default='characteristic', max_length=18)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('duration', models.TimeField(null=True)),
                ('explain', models.TextField(max_length=500)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.placename')),
            ],
        ),
    ]
