# Generated by Django 3.1 on 2020-08-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='ver',
            field=models.CharField(max_length=12, null=True, verbose_name='Ver 1.0.0'),
        ),
    ]
