# Generated by Django 3.1 on 2020-08-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_version_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='ver',
            field=models.CharField(default='Ver 1.0.0', max_length=12, null=True),
        ),
    ]
