# Generated by Django 3.1 on 2020-09-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('explain', models.CharField(max_length=500)),
            ],
        ),
    ]
