# Generated by Django 3.1 on 2020-09-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='explain',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
