# Generated by Django 3.1 on 2020-09-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200903_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='chara',
            field=models.CharField(choices=[('characteristic', '特徴'), ('landscape', '風景'), ('history', '歴史'), ('theme park', '遊園地'), ('leisure facilities', 'レジャー施設'), ('sports', 'スポーツ'), ('food', '食事処'), ('spring', '温泉'), ('amusement', '娯楽'), ('nature', '自然'), ('art', '芸術'), ('world heritage', '世界遺産'), ('souvenir', 'お土産')], default='characteristic', max_length=18),
        ),
    ]
